// @flow

import {Dimensions, Platform} from 'react-native'

const { width, height } = Dimensions.get('window')

// Used via Metrics.baseMargin
const metrics = {
  marginHorizontal: 10,
  marginVertical: 10,
  section: 25,
  baseMargin: 10,
  doubleBaseMargin: 20,
  smallMargin: 5,
  extraSmallMargin: 3,
  horizontalLineHeight: 1,
  searchBarHeight: 30,
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
  navBarHeight: (Platform.OS === 'ios') ? 64 : 54,
  icons: {
    tiny: 15,
    small: 20,
    medium: 30,
    large: 45,
    xl: 60
  },
  images: {
    small: 20,
    medium: 40,
    large: 60,
    logo: 300
  },
  feedHeaderHeight: 30,
  contactsHeaderHeight: 45,
  feedItemHeight: 67.5,
  contactsItemHeight: 51,
  separatorHeight: 1,
  separatorMargin: width * 0.19,
  feedPhotoWidth: width * 0.19,
  feedPhoto: 40,
  contactsPhoto: 30,
  feedIcon: 12,
  borderRadius: 20,
  borderRadiusSmall: 15,
  swipeoutIcon: 17,
  contactsCheckbox: 20,
  marginCheckBox: width * 0.04,
  marginContactsPhoto: width * 0.05,
  borderContactsCheckbox: 2,
  searchIcon: 15,
  rowHeight: height * 0.072,
  recurrenceSectionTop: height * 0.053,
  rowBaseMargin: 15,
  arrow: 15,
  footer: 50,
  addBtnMargin: 8,
  addBtnWidth: width * 0.22,
  addBtnAlignRight: width * 0.515,
  swiperMargin: height * 0.05,
  swiperItemsMargin: 15,
  smallBorderRadius: 5,
  navBarOccurrence: height * 0.09,
  customNavBarMargin: width * 0.03,
  customNavBarLeftIcon: 15,
  customNavBarButton: width * 0.2,
  swiperItemBottom: height * 0.13,
  // occurrenceItemHeader: height * 0.13,
  occurrenceItemPhoto: height * 0.14,
  occurrenceItemPhotoRadius: height * 0.07,
  occurrenceItemHeaderTop: height * 0.05,
  occurrenceItemMargin: height * 0.02,
  occurrenceItemInfoTop: height * 0.03,
  occurrenceItemInfoLeft: width * 0.025,
  occurrenceItemInfoRow: width * 0.033,
  occurrenceItemInfoRowBot: width * 0.02,
  buttonHeight: height * 0.08,
  buttonWidth: width * 0.43,
  buttonRadius: width * 0.01,
  occurrenceItemIcon: width * 0.15,
  recurrenceButton: width * 0.93,
  alertWidth: width * 0.73,
  alertHeight: width * 0.73,
  footerTextOpacity: (Platform.OS === 'ios') ? 0.55 : 0.3,
  settingsHeader: height * 0.08,
  settingsTitlePaddingLeft: 15,
  sourceItemHeight: height * 0.11,
  sourceItemIcon: width * 0.135,
  sourceItemIconMargin: width * 0.04,
  sourceItemIconRadius: 5,
  sourceTitleTop: 3,
  navBarTitle: 7,
  footerIcon: 6,
  alertButtonHeight: 50,
  alertImage: width * 0.24,
  alertSkipHeight: 60,
  alertMargin: 15,
  navBarIcon: 11,
  border: 0.5,
  deleteBtnMargin: 15,
  sectionReminderPadding: 4,
  wheelPickerHeight: 200,
}

export default metrics
